### ISSUE TITLE
RealTimeSource cannot recognize [DisplayAttribute] in binded model class

### ISSUE THREAD

**Issue by BigDream324** [DevExpress-Examples/dxgrid-how-to-use-realtimesource-e4748#1]
when I bind a RealTimeSource to a GridControl, all the properties was displayed,but I set the `[Display(AutoGenerateField = false)]` to the property.
If I bind the collection to the GridControl directly, DisplayAttribute works normal.

**Comment by MichaelDX** [comment]
Hello @BigDream324,

We are using our Support Center as a primary channel to offer support services to our customers. So, if you encountered some issues when using DevExpress WPF components, please submit a ticket to our [Support Center](https://supportcenter.devexpress.com/) and describe the issue you faced. Our Support Team will be happy to help you.

We will appreciate it if you attach a sample project demonstrating the issue in action. This way, we will focus on the problematic area and assist you more effectively.

Thanks,
Michael
